### ISSUE TITLE
File Sharing

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#23] opened 2023-07-13 20:15 UTC
As a content developer, I should have a space in the data list where I can insert files into social shared messages. 
As a facilitator, I should be able to share messages containing files, such as images or videos. 
When images are shared, there should be an option to append text to the image, such that a comic can be distributed through social media sharing.

**Comment by esmeetewinkel** [comment] 2024-01-23 15:03
Duplicate of #51, closing here

**Closed by esmeetewinkel** 2024-01-23 15:03 UTC
